<div class="container">

	<div class="row">
		<?php 
			//insert blocks here
			//insert_block($tag, $content, $id, $classes)
			//insert_raw($content)
		?>
	</div>

	<div class="row">
		<?php 
			//insert blocks here
			//insert_block($tag, $content, $id, $classes)
			//insert_raw($content)
		?>
	</div>

	<div class="row">
		<?php 
			//insert blocks here
			//insert_block($tag, $content, $id, $classes)
			//insert_raw($content)
		?>
	</div>
	
</div>