<?php

$title='<img src="assets/img/icon-call.svg" alt="call" class="img-circle">
		<img src="assets/img/dots.svg" alt"" aria-hidden="true" class="dots hidden-xs hidden-sm img-responsive">
		<hr>
		<h3>Make a Claim</h3>';

$body='<p>Just call<a href="tel:+18003871963" id="cta2Link"><strong>1 800 387 1963</strong></a> anytime, anywhere</p>';
					
$contObj = (object) array('title' => $title, 'body' => $body);

?>