<?php

$title='<img src="assets/img/icon-smartTips.svg" alt="smartTips" class="img-circle">
		<img src="assets/img/dots.svg" alt"" aria-hidden="true" class="dots hidden-xs hidden-sm img-responsive">
		<hr>
		<h3>Get SmartTips</h3>';

$body='<p>Advice to <a href="#" id="cta3Link">stay safe, protect your home, and save</a></p>';
					
$contObj = (object) array('title' => $title, 'body' => $body);
?>