<?php

$title='<img src="assets/img/icon-group.svg" alt="group plans" class="img-circle">
		<img src="assets/img/dots.svg" alt"" aria-hidden="true" class="dots hidden-xs hidden-sm img-responsive">
		<hr>
		<h3>Be a Group Sponsor</h3>';

$body='<p>Everyone saves on rates with a <a href="#" id="cta4Link">Group Insurance Plan</a></p>';
					
$contObj = (object) array('title' => $title, 'body' => $body);

?>