        <footer class="footer">
        	<div class="container">
        		<p><a href="#">Accessibility Policy</a>  |   <a href="#">Legal</a>   |   <a href="#">Privacy Policy</a>   |   <a href="#">Fraud Alert</a>    |   <a href="#">Contact Us</a></p>

        		<p>© 2014 COSECO Insurance Company</p>
        	</div>
        </footer>		

        <script src="assets/js/app.min.js"></script>
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/bootstrap.min.js"></script>
        <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', App.settings.ga.urchin, App.settings.ga.url);
        ga('send', 'pageview');
        
        </script>