			<div class="top-bar blueBarDark">
				<div class="container" id="topBar">
					<div class="navbar-left contactArea pull-left">
						<img src="assets/img/icon-topBar-call.svg" class="hidden-xs" alt="call"><span class="hidden-xs">Let’s talk </span><a href="tel:+18003871963" id="topBarTel"><strong>1 800 387 1963</strong></a>&nbsp;&nbsp;&nbsp;<a href="#" id="topBarManage">Manage My Policy</a>
					</div>
	      			<div class="pull-right contactArea">
					<div class="navbar-form hidden-xs pull-left" role="search" id="topBarSearch">
						<label for="search" class="sr-only">Search</label>
	        			<input type="text" class="form-control" placeholder="Search" id="search">
	        			<button type="submit" class="btn btn-secondary btn-xs" title="Submit a search request">Submit</button>
	      			</div>
					<a href="#" id="topBarLang">FR</a>
					</div>
				</div>
			</div>

		<header class="page-header hidden-xs">
			<div class="container">	
				<a href="index.html" alt="Coseco Home"><img src="assets/img/logo.svg" alt="Coseco" class="img-responsive"></a>
			</div>
		</header>
	
	<nav id="mainNavigation" class="navbar-default cosecoNav">
		<div class="container">	
			<div class="row">
				<div class="navbar-header visible-xs-block">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	              		<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">
						<img src="assets/img/logo.svg" alt="Coseco" class="img-responsive mobileLogo pull-left">
					</a>
				</div>
			  		
				<div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;" role="navigation">
					<ul class="nav navbar-nav">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Insurance <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="auto.html">Auto Insurance</a></li>
								<li><a href="home.html">Home Insurance</a></li>
								<li><a href="travel.html">Travel Insurance</a></li>
							</ul>
						</li>
						<li><a href="#">Claims</a></li>
						<li><a href="#">Discounts</a></li>
						<li><a href="#">SmartTips</a></li>
						<li><a href="#">Insure My Group</a></li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
	</nav>