<?php

$title='<h1>When it comes to great rates, there’s strength in numbers.</h1>';

$body='<p>We believe that group membership should come with a few perks—like great rates on your auto and home insurance. All it takes is a few seconds to get the coverage you need at a price that’s right.</p>
<button class="btn btn-lg btn-primary" type="button" id="carouselHomeBtn"><i class="fa fa-home"></i> Get a home quote now</button>
<button class="btn btn-lg btn-primary" type="button" id="carouselAutoBtn"><i class="fa fa-car"></i> Get an auto quote now</button>';

$contObj = (object) array('title' => $title, 'body' => $body);

?>