<?php

$title='<img src="assets/img/icon-myPolicy.svg" alt="My Policy"  class="hidden-xs hidden-sm">
<h3>My Policy</h3>';

$body='<p>View your policy details, make a claim, request e-policy delivery, manage your billing, and more</p>
<button class="btn btn-lg btn-secondary" type="button" id="myPolicyLoginBtn">Login</button>
<button class="btn btn-lg btn-default" type="button" id="myPolicySignUpBtn">Sign Up</button>';

$contObj = (object) array('title' => $title, 'body' => $body);

?>