<div class="container">
	<div id="carousel" class="row">
		<?php insert_block('section', 'mainbanner', 'mainBanner', 'col-md-9'); ?>
		<?php insert_block('section', 'mypolicy', 'myPolicy', 'col-md-3'); ?>
	</div>

	<div id="serviceRow" class="row">
		<?php insert_block('section', 'cta1', 'cta1', 'col-sm-3'); ?>
		<?php insert_block('section', 'cta2', 'cta2', 'col-sm-3'); ?>
		<?php insert_block('section', 'cta3', 'cta3', 'col-sm-3'); ?>
		<?php insert_block('section', 'cta4', 'cta4', 'col-sm-3'); ?>
	</div>
</div>